import type { Metadata } from "next";
import "./globals.css";
import "@aws-amplify/ui-react/styles.css";
import '@/components/ConfigureAmplify'

import ConfigureAmplifyClientSide from "@/components/ConfigureAmplify";

export const metadata: Metadata = {
  title: "Tampa Dynamics",
  description: "Generated by Tampa Dynamics",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      > <ConfigureAmplifyClientSide />
        {children}
      </body>
    </html>
  );
}
